# Building Better Recommendations

Recommendations are big business. Amazon reports that 35% of its revenue comes from recommendations. Even more surprisingly, Netflix and Youtube report that 75 and 70% of what people watch on their platforms comes from recommendations.

So how do we build a good recommendation engine? Well, follow along to find out!

In [1]:
from graphdatascience.session import DbmsConnectionInfo, AlgorithmCategory, CloudLocation, GdsSessions, AuraAPICredentials
from datetime import timedelta
import pandas as pd
import os
from dotenv import load_dotenv

## Authentication & Session Setup

### Authentication
You must first generate your credentials in Neo4j Aura. Afterwards, you can store your credentials securely using a `.env` file (copy `.env.example` to `.env` and fill it in).

In [4]:
load_dotenv()

# This credential is the Organization ID
TENANT_ID = os.environ["TENANT_ID"]

# These credentials were generated after the creation of the API Endpoint
CLIENT_SECRET = os.environ["CLIENT_SECRET"]
CLIENT_ID = os.environ["CLIENT_ID"]

# These credentials were generated after the creation of the Aura Instance
NEO4J_URI = os.environ["NEO4J_URI"]
NEO4J_USERNAME = os.environ.get("NEO4J_USERNAME", "neo4j")
NEO4J_PASSWORD = os.environ["NEO4J_PASSWORD"]

## Establishing a Session

Estimate resources based on graph size and create a session with a 2‑hour TTL.

In [5]:
sessions = GdsSessions(api_credentials=AuraAPICredentials(CLIENT_ID, CLIENT_SECRET, TENANT_ID))

session_name = "demo-session"
memory = sessions.estimate(
    node_count=1000, relationship_count=5000,
    algorithm_categories=[AlgorithmCategory.CENTRALITY, AlgorithmCategory.NODE_EMBEDDING],
)

db_connection_info = DbmsConnectionInfo(NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD)

In [6]:
# Initialize a GDS session scoped for 2 hours, sized to estimated graph
gds = sessions.get_or_create(
    session_name,
    memory=memory,
    db_connection=db_connection_info, # this is checking for a bolt server currently
    ttl=timedelta(hours=2),
)

print("GDS session initialized.")

GDS session initialized.

## Our Data

We are going to be working with a dataset put together by instacart. It looks at different orders from a grocery store. We will use this to put together product recommendations.

Our data is currently in this format:
```
(User)-[PLACED]->(Order)-[CONTAINS]->(Product)-[IN_AISLE]->(Aisle)-[IN_DEPARTMENT]->(Department)
```
For our purposes, we are actually going to be working with a subset of this graph. We are going to create a co-purchase graph. Basically, we will see what items are purchased in the same market basket.

But before we do that, let's first take a look at the top items that are copurchased together.

In [7]:
query = """MATCH (o:Order)-[:CONTAINS]->(p1:Product),
      (o)-[:CONTAINS]->(p2:Product)
WHERE id(p1) < id(p2)
RETURN p1.name AS productA,
       p2.name AS productB,
       count(*) AS timesTogether
ORDER BY timesTogether DESC
LIMIT 5;"""

df = gds.run_cypher(query)
df

Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. id is deprecated. It is replaced by elementId or consider using an application-generated id.', position=<SummaryInputPosition line=3, column=7, offset=85>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 85, 'line': 3, 'column': 7}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: 'MATCH (o:Order)-[:CONTAINS]->(p1:Product),\n      (o)-[:CONTAINS]->(p2:Product)\nWHERE id(p1) < id(p2)\nRETURN p1.name AS productA,\n       p2.name AS productB,\n       count(*) AS timesTogether\nORDER BY timesTogether DESC\nLIMIT 5;'
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. id is deprecated. It is replaced by elementId or consider using an application-generated id.', position=<SummaryInputPosition line=3, column=16, offset=94>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 94, 'line': 3, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: 'MATCH (o:Order)-[:CONTAINS]->(p1:Product),\n      (o)-[:CONTAINS]->(p2:Product)\nWHERE id(p1) < id(p2)\nRETURN p1.name AS productA,\n       p2.name AS productB,\n       count(*) AS timesTogether\nORDER BY timesTogether DESC\nLIMIT 5;'

                 productA              productB  timesTogether
0    Organic Baby Spinach                Banana             24
1  Bag of Organic Bananas  Organic Hass Avocado             22
2  Bag of Organic Bananas  Organic Strawberries             19
3                  Banana       Organic Avocado             16
4    Organic Strawberries  Organic Hass Avocado             15

 You will notice that four out of five of the top co-purchased pairs includes bananas. Logically, I suppose this means that grocery stores should nearly always recommend bananas to customers?

 Let's keep working through and see if that holds up.

 ## Creating a Graph Projection

 Now that we have a good idea of whats in our data, let's break down the query needed to generate a graph projection.

**For the inner projection:**

First, we find orders that contain two given products. We then add in a filter that ensures we don't have duplicate pairs.

```
MATCH (o:Order)-[:CONTAINS]->(p1:Product),
      (o)-[:CONTAINS]->(p2:Product)
WHERE p1.product_id < p2.product_id
```
We use `<` to ensure that we don't count each pair twice. So if we had Milk (id: 1) and Bread (id: 2), we get (1, 2) but not also (2, 1).

Next, we count the number of times that combination occurs and save it as a float:
```
WITH p1, p2, toFloat(COUNT(*)) AS weight
```
Finally, we return our values:
```
RETURN p1 AS source, p2 AS target, weight
```
**For the outer projection:**
We first grab what we returned from the inner projection, starting with the start and end nodes for our new relationship:

```
RETURN gds.graph.project.remote(
    source,
    target,
    {
    sourceNodeLabels: labels(source),
    targetNodeLabels: labels(target),
```
And then we give a name to the relationship:
```
relationshipType: 'CO_PURCHASED_WITH',
```
And finally, we pull in our weight property. Because we named our count as weight in the triplet from the inner query (source, target, weight), we have to access it like so:
```
relationshipProperties: {weight: weight}
```

In [8]:
gds.graph.drop("copurchase", fail_if_missing=False)

query = """
CALL {
    MATCH (o:Order)-[:CONTAINS]->(p1:Product),
          (o)-[:CONTAINS]->(p2:Product)
    WHERE p1.product_id < p2.product_id
    WITH p1, p2, toFloat(COUNT(*)) AS weight
    RETURN p1 AS source, p2 AS target, weight
}
RETURN gds.graph.project.remote(
    source,
    target,
    {
        sourceNodeLabels: labels(source),
        targetNodeLabels: labels(target),
        relationshipType: 'CO_PURCHASED_WITH',
        relationshipProperties: {weight:weight}
        }

);
"""

copurchase_graph, result = gds.graph.project.cypher(
    graph_name="copurchase",
    query=query
)

Graph creation from Triplets: 100%|██████████| 100.0/100 [00:02<00:00, 39.35%/s, status: FINISHED]

Next, we will run nodeSimilarity to see which products tend to be purchased together. Let's break down exactly what we are looking at. Imagine, if we had only three baskets:

| Basket | Products             |
|--------|----------------------|
| 1      | Eggs, Bread, Milk    |
| 2      | Bread, Milk, Butter  |
| 3      | Eggs, Bread, Butter  |

We can see that eggs tend to be purchased with bread, and that butter tends to be purchased with bread. So we can therefore say, eggs and butter are likely to be purchased together since they commonly share neighbors in their baskets (in this case bread). Items that share a lot of neighbors are considered to be similar to eachother.

That's one half of how that algorithm works. Bread in the above example actually appears in every basket, so it really doesn't provide us that much information (since it is a shared neighbor with every item). Luckily, Node Similarity discounts items that have too many neighbors.

Now imagine a case where:

| Basket | Products             |
|--------|----------------------|
| 1      | Eggs, Bread, Milk    |
| 2      | Bread, Milk, Butter  |
| 3      | Eggs, Bread, Butter  |
| 4      | Wine, Crackers, Bread  |
| 5      | Cheese, Crackers, Bread  |

The similarity between cheese and wine will largely be driven by the presence of crackers than bread because bread is mostly noise (and empty calories). Again, this is because bread is in every basket and therefore, its presence is not a good predictor of what other items will be in the basket.

Enough talk, let's run the algorithm:

In [10]:
result = gds.node_similarity.write(
    copurchase_graph,
    top_k=10,
    relationship_weight_property="weight",
    write_relationship_type="SIMILAR_TO",
    write_property="score"
)

result

Node Similarity: 100%|██████████| 100.0/100 [00:01<00:00, 74.97%/s, status: FINISHED]
Write-Back (graph: copurchase): 100%|██████████| 100.0/100 [00:00<00:00, 132.86%/s, status: FINISHED]

NodeSimilarityWriteResult(pre_processing_millis=0, compute_millis=1165, write_millis=1001, post_processing_millis=0, nodes_compared=4129, relationships_written=40524, similarity_distribution={'p95': 0.8333358727395535, 'p10': 0.13207625970244408, 'p5': 0.10000037774443626, 'mean': 0.36731990520067326, 'p90': 0.7272758446633816, 'p75': 0.5000038109719753, 'stdDev': 0.22576436313161233, 'p1': 0.05000018700957298, 'max': 1.000007629394531, 'p100': 1.000007625669241, 'p50': 0.3098602257668972, 'p25': 0.20000075921416283, 'min': 0.0008561611175537109, 'p99': 1.000007625669241}, configuration={'similarityCutoff': 1e-42, 'similarityMetric': 'JACCARD', 'degreeCutoff': 1, 'upperDegreeCutoff': 2147483647, 'topK': 10, 'topN': 0, 'bottomK': 10, 'bottomN': 0, 'useComponents': False, 'relationshipTypes': ['*'], 'nodeLabels': ['*'], 'sudo': False, 'logProgress': True, 'concurrency': 1, 'jobId': '02c82f18-bcee-4d98-8d72-0c2a328f8a07', 'relationshipWeightProperty': 'weight', 'writeProperty': 'similarity', 'writeConcurrency': 1, 'writeToResultStore': True, 'writeRelationshipType': 'SIMILAR'})

In our actual dataset, you'll notice that bananas are co-purchased with nearly everything — and for that reason, they mostly represent noise.

In fact, if you look at the **least similar items**, bananas often top the list. Why?

Because their presence in a basket doesn’t really signal that the customer wants any other specific item — they’re just a frequent, general-purpose purchase.

So while bananas are everywhere, they tell us almost nothing about co-purchase patterns — and `nodeSimilarity` correctly learns to **downweight** them. And this is why using node similarity provides some value over simply looking at what items are co-purchased together the most.

In [11]:
query = """
MATCH (p1:Product)-[r:SIMILAR_TO]->(p2:Product)
RETURN p1.product_id AS product1_id, p1.name AS product1_name,
       p2.product_id AS product2_id, p2.name AS product2_name,
       r.score AS similarity_score
ORDER BY similarity_score
LIMIT 10
"""

gds.run_cypher(query)

,product1_id,product1_name,product2_id,product2_name,similarity_score
0,41605,Chocolate Bar Milk Stevia Sweetened Salted Almond,13176,Bag of Organic Bananas,0.000856
1,31478,DairyFree Cheddar Style Wedges,13176,Bag of Organic Bananas,0.000856
2,41162,Grapes Certified Organic California Black Seed...,13176,Bag of Organic Bananas,0.000856
3,41605,Chocolate Bar Milk Stevia Sweetened Salted Almond,13176,Bag of Organic Bananas,0.000856
4,41162,Grapes Certified Organic California Black Seed...,13176,Bag of Organic Bananas,0.000856
5,31478,DairyFree Cheddar Style Wedges,13176,Bag of Organic Bananas,0.000856
6,40945,Baking Chopped Pecans,24852,Banana,0.000887
7,38890,No Pulp Calcium Vitamin D Pure Premium Pure Or...,24852,Banana,0.000887
8,38290,Vegan Crunchy Peanut Butter,24852,Banana,0.000887
9,38890,No Pulp Calcium Vitamin D Pure Premium Pure Or...,24852,Banana,0.000887

In [12]:
sessions.delete(session_name=session_name)

True